server:
  port: 10002
spring:
  kafka:
    bootstrap-servers: 192.168.1.101:9092,192.168.1.102:9092,192.168.1.103:9092
    producer:
      # 消息发送确认方式，默认为0，表示不等待确认，1表示等待leader确认，-1表示等待所有副本确认
      acks: 0
      # 消息重试次数，默认为0不重试
      retries: 3
      # 发送缓冲区大小，默认为33554432
      buffer-memory: 33554432
      # 发送数据的压缩类型，默认为none
      compression-type: none
    consumer:
      # 消费组ID
      group-id: test-group
      # 消费者每次poll的最大数量
      max-poll-records: 100
      # 消息自动提交的时间间隔，单位为ms
      auto-commit-interval: 1000
      # 是否自动提交offset，默认为true
      enable-auto-commit: true
      # 从最早的消息开始消费，earliest表示从最早的消息开始消费，latest表示从最新的消息开始消费
      auto-offset-reset: earliest
logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG